<?php

include_once('ca_state_questions.features.inc');

/**
 * Implementation of hook_perm().
 */
function ca_state_questions_perm() {
  return array('ca_state_questions change templates'); 
}

/**
 * Implementation of hook_menu().
 */
function ca_state_questions_menu() {
  $items['admin/settings/ca_state_questions'] = array(
    'title' => 'CA State Question: Admin',
    'description' => 'Change the look and feel of the ca_state_questions module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_state_question_administrator_settings_form'),
    'access arguments' => array('ca_state_questions change templates'),
    'file' => 'ca_state_questions.admin.inc',
    'file path' => drupal_get_path('module', 'ca_state_questions') . '/includes',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function ca_state_questions_action_info() {
  return array(
    'ca_state_questions_add_state_question_administrator_action' => array(
      'type' => 'user',
      'description' => t('Add state question administrator role'),
    ),
    'ca_state_questions_remove_state_question_administrator_action' => array(
      'type' => 'user',
      'description' => t('Remove state question administrator role'),
    ),
  );
}

function ca_state_questions_add_state_question_administrator_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'state question administrator') {
      $add_roles[$key] = $role;
    }
  }
  $roles += $add_roles;
  user_save($user, array('roles' => $roles));
}

function ca_state_questions_add_state_question_administrator_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Promote to State Question Administrator',
  );
  return $form;
}

function ca_state_questions_add_state_question_administrator_action_submit(&$form, &$form_state) {
  
}

function ca_state_questions_remove_state_question_administrator_action($user, $context) {
  $available_roles = user_roles(TRUE);
  $roles = $user->roles;
  foreach ($available_roles as $key => $role) {
    if ($role == 'state question administrator') {
      $remove_roles[$key] = $role;
    }
  }
  $roles = array_diff($roles, $remove_roles);
  user_save($user, array('roles' => $roles));
}

function ca_state_questions_remove_state_question_administrator_action_form() {
  $form = array();
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Demote from State Question Administrator',
  );
  return $form;
}

function ca_state_questions_remove_state_question_administrator_action_submit(&$form, &$form_state) {
  
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function ca_state_questions_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;;
  }
}

/**
 * Implementation of hook_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask).
 */
function ca_state_questions_ctools_render_alter($info, $page, $args, $contexts, $task, $subtask){
  if ($subtask['name'] == 'ca_state_questions' || $subtask['name'] == 'home' || $task['name'] == 'node_view') {
    drupal_add_css(drupal_get_path('module', 'ca_state_questions') . "/css/ca_state_questions.css", 'module', 'all', FALSE);
  }
}

/**
 * Implementation of hook_views_pre_render().
 */
function ca_state_questions_views_pre_render(&$view) {
  if ($view->name == 'ca_state_questions') {
    drupal_add_css(drupal_get_path('module', 'ca_state_questions') . "/css/ca_state_questions.css", 'module', 'all', FALSE);
  }
}
