<?php

/**
 * Implementation of hook_install().
 */
function ca_state_questions_install() {
  variable_set('ca_state_questions_list_template', 'ca_state_questions_list_template_one');
  variable_set('ca_state_questions_node_template', 'ca_state_questions_node_template_one');
}

/**
 * Implementation of hook_uninstall().
 */
function ca_state_questions_uninstall() {
  variable_del('ca_state_questions_list_template');
  variable_del('ca_state_questions_node_template');
}
